services:
  - type: web
    name: ticketing-system
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ticketing-system.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"
    plan: free
